version: '3'

services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
      - "5173:5173"
    depends_on:
      - db
      - redis
      - elastic

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
  elastic-admin:
    image: stephanediondev/elasticsearch-admin
    ports:
      - "8090:8080"
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200

volumes:
  db-data:
  elastic-data:
